#!/data/data/com.termux/files/usr/bin/bash
# -*- coding: utf-8 -*-
# Shortcut script para ejecutar el setup (update-upgrade)

set -e
set -u

cd "$HOME/libre-gallinero"

# Cargar funciones comunes
source "$HOME/libre-gallinero/termux/common.sh"

# Ejecutar setup
if ./termux/termux-setup.sh; then
    pause_success
else
    pause_error "Setup falló"
fi

